## Imports

In [1]:
import sys
sys.executable # sanity check to make sure the env is correct

'/home/dave/anaconda3/bin/python'

In [2]:
import json
import pandas as pd
import numpy as np
import tqdm
from tqdm import tqdm
import ollama
from ollama import AsyncClient
from multiprocessing import Pool, cpu_count
import time
import re
import os
import asyncio

## Key Functions

In [18]:
# PROCESS DF -- SPLITS A DATAFRAME INTO n CHUNKS AND ASSIGNS m WORKERS TO PROCESS EACH CHUNK -- NEW
def process_df(df, num_chunks=200, workers=2, output_dir=''):
    print("Splitting df into chunks")
    chunks = np.array_split(df, num_chunks)
    work_items = []

    for chunk_id, chunk in enumerate(chunks):
        filename = f"chunk{chunk_id}.parquet"
        filepath = os.path.join(output_dir,filename)

        if os.path.exists(filepath):
            print(f"skipping chunk {chunk_id} (already exists)")
            continue

        work_items.append((chunk, chunk_id, output_dir))
    
    
    start_time = time.time()

    results = []
    with Pool(workers) as p:
        results = list(
            tqdm(
                p.imap(filter_chunk, work_items),
                total=len(work_items),
                desc="Filtering rows"
            )
        )
    end_time = time.time() - start_time
    print('processing tool:',end_time, ' seconds')
    
    return pd.concat(results, ignore_index=True)

In [141]:
# PROCESS DF -- SPLITS A DATAFRAME INTO n CHUNKS AND ASSIGNS m WORKERS TO PROCESS EACH CHUNK -- ORIGINAL
'''def process_df(df, num_chunks=200, workers=2):
    chunks = np.array_split(df, num_chunks)
    start_time = time.time()
    with Pool(workers) as p:
        results = list(
            tqdm(
                p.imap(filter_chunk, chunks),
                total=num_chunks,
                desc="Filtering rows"
            )
        )
    end_time = time.time() - start_time
    print('processing tool:',end_time, ' seconds')
    return pd.concat(results, ignore_index=True)'''

'def process_df(df, num_chunks=200, workers=2):\n    chunks = np.array_split(df, num_chunks)\n    start_time = time.time()\n    with Pool(workers) as p:\n        results = list(\n            tqdm(\n                p.imap(filter_chunk, chunks),\n                total=num_chunks,\n                desc="Filtering rows"\n            )\n        )\n    end_time = time.time() - start_time\n    print(\'processing tool:\',end_time, \' seconds\')\n    return pd.concat(results, ignore_index=True)'

In [16]:
# FILTER CHUNK -- EXECUTES A PROCESS ON EACH ITEM IN A SERIES -- NEW
async def filter_chunk_async(df_chunk, chunk_id,output_dir):
    chunk = df_chunk.copy()

    # PROCESS ROWS
    tasks = [process_row(row['description']) for _, row in chunk.iterrows()]
    #results = await asyncio.gather(*tasks)
    results = []
    for coro in tqdm(
        asyncio.as_completed(tasks),
        total=len(tasks),
        desc=f"Chunk {chunk_id}"
    ):
        result = await coro
        results.append(result)
    
    chunk['embeddings'] = results
    
    # NAME COMPLETED CHUNK AND SAVE AS CSV
    filename = f"chunk{chunk_id}.parquet"
    filepath = os.path.join(output_dir,filename)
    chunk.to_parquet(filepath, index=False)
    
    return chunk

def filter_chunk(args):
    df_chunk, chunk_id, output_dir = args
    return asyncio.run(filter_chunk_async(df_chunk, chunk_id, output_dir))

In [142]:
# FILTER CHUNK -- EXECUTES A PROCESS ON EACH ITEM IN A SERIES -- ORIGINAL
'''async def filter_chunk_async(df_chunk):
    chunk = df_chunk.copy()

    # PROCESS ROWS
    tasks = [process_row(row['description']) for _, row in chunk.iterrows()]
    results = await asyncio.gather(*tasks)
    chunk['embeddings'] = results
    
    return chunk

def filter_chunk(chunk):
    return asyncio.run(filter_chunk_async(chunk))'''

"async def filter_chunk_async(df_chunk):\n    chunk = df_chunk.copy()\n\n    # PROCESS ROWS\n    tasks = [process_row(row['description']) for _, row in chunk.iterrows()]\n    results = await asyncio.gather(*tasks)\n    chunk['embeddings'] = results\n\n    return chunk\n\ndef filter_chunk(chunk):\n    return asyncio.run(filter_chunk_async(chunk))"

In [12]:
# PROCESS ROW -- OPERATES ON ONE ITEM IN A SERIES
async def process_row(text):
    try:
        ollama = AsyncClient()
        response = await ollama.embeddings(model="mxbai-embed-large",prompt=text)        
        return response["embedding"]
        
    except Exception as e:
        return None

## Input DataFrame

In [13]:
df = pd.read_csv("/home/dave/dataCleanupUtility/target/clean_rows.csv")
df.head()

,Unnamed: 0,title,description
0,0,Glass Town,"A brief, fictionalized account of the daily li..."
1,1,Coretta Scott King,Explores the life and career of Coretta Scott ...
2,2,A tawdry place of salvation,In this first critical study of the work of Ja...
3,3,Inside COM,"""Microsoft's Component Object Model (COM) has ..."
4,4,Thunderbird gold,"While visiting his cousin in northern Canada, ..."

In [14]:
df = df[['title','description']]
df.head()

,title,description
0,Glass Town,"A brief, fictionalized account of the daily li..."
1,Coretta Scott King,Explores the life and career of Coretta Scott ...
2,A tawdry place of salvation,In this first critical study of the work of Ja...
3,Inside COM,"""Microsoft's Component Object Model (COM) has ..."
4,Thunderbird gold,"While visiting his cousin in northern Canada, ..."

## Testing

In [8]:
df_test = df.head(100)
df_test.head()

,title,description
0,Glass Town,"A brief, fictionalized account of the daily li..."
1,Coretta Scott King,Explores the life and career of Coretta Scott ...
2,A tawdry place of salvation,In this first critical study of the work of Ja...
3,Inside COM,"""Microsoft's Component Object Model (COM) has ..."
4,Thunderbird gold,"While visiting his cousin in northern Canada, ..."

In [8]:
process_df(df_test,workers=2, num_chunks=25)

NameError: name 'df_test' is not defined

## Benchmarking

In [129]:
def benchmark(df, max_workers=4, num_chunks=200):
    results = []
    outputs = []
    
    for n in range(1, max_workers +1):
        print(f"\nTesting with {n} worker(s)...")

        start = time.time()
        processed = process_df(df, workers=n, num_chunks=num_chunks)
        end = time.time()

        processed = processed.copy()
        processed['workers'] = n

        outputs.append(processed)
        
        results.append({
            "workers":n,
            "elapsed time": end - start
        })
    times_df = pd.DataFrame(results)
    outputs_df = pd.concat(outputs, ignore_index=True)
    return times_df, outputs_df

In [130]:
times_df, outputs = benchmark(df_test, max_workers =4, num_chunks=25)

Testing with 1 worker(s)...

/home/dave/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
Filtering rows: 100%|██████████| 25/25 [00:13<00:00,  1.86it/s]

processing tool: 14.167255878448486  seconds

Testing with 2 worker(s)...

/home/dave/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
Filtering rows: 100%|██████████| 25/25 [00:06<00:00,  3.79it/s]

processing tool: 7.675982713699341  seconds

Testing with 3 worker(s)...

/home/dave/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
Filtering rows: 100%|██████████| 25/25 [00:05<00:00,  4.70it/s]

processing tool: 6.680152416229248  seconds

Testing with 4 worker(s)...

/home/dave/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
Filtering rows: 100%|██████████| 25/25 [00:04<00:00,  5.45it/s]

processing tool: 6.103870630264282  seconds

In [92]:
times_df

   workers  elapsed time
0        1      9.849763
1        2      5.912042
2        3      5.141709
3        4      4.658275

In [97]:
outputs.groupby("workers").head()

,title,description,embeddings,workers
0,Glass Town,"A brief, fictionalized account of the daily li...","[0.1728658378124237, -0.33320003747940063, 0.2...",1
1,Coretta Scott King,Explores the life and career of Coretta Scott ...,"[-0.3468349575996399, -0.21785852313041687, -0...",1
2,A tawdry place of salvation,In this first critical study of the work of Ja...,"[-0.11076848208904266, -1.3954136371612549, -0...",1
3,Inside COM,"""Microsoft's Component Object Model (COM) has ...","[-0.4319303333759308, -0.4709661602973938, -0....",1
4,Thunderbird gold,"While visiting his cousin in northern Canada, ...","[0.2797992527484894, 0.21501488983631134, 0.27...",1
100,Glass Town,"A brief, fictionalized account of the daily li...","[0.1728658378124237, -0.33320003747940063, 0.2...",2
101,Coretta Scott King,Explores the life and career of Coretta Scott ...,"[-0.3468349575996399, -0.21785852313041687, -0...",2
102,A tawdry place of salvation,In this first critical study of the work of Ja...,"[-0.11076848208904266, -1.3954136371612549, -0...",2
103,Inside COM,"""Microsoft's Component Object Model (COM) has ...","[-0.4319303333759308, -0.4709661602973938, -0....",2
104,Thunderbird gold,"While visiting his cousin in northern Canada, ...","[0.2797992527484894, 0.21501488983631134, 0.27...",2
200,Glass Town,"A brief, fictionalized account of the daily li...","[0.1728658378124237, -0.33320003747940063, 0.2...",3
201,Coretta Scott King,Explores the life and career of Coretta Scott ...,"[-0.3468349575996399, -0.21785852313041687, -0...",3
202,A tawdry place of salvation,In this first critical study of the work of Ja...,"[-0.11076848208904266, -1.3954136371612549, -0...",3
203,Inside COM,"""Microsoft's Component Object Model (COM) has ...","[-0.4319303333759308, -0.4709661602973938, -0....",3
204,Thunderbird gold,"While visiting his cousin in northern Canada, ...","[0.2797992527484894, 0.21501488983631134, 0.27...",3
300,Glass Town,"A brief, fictionalized account of the daily li...","[0.1728658378124237, -0.33320003747940063, 0.2...",4
301,Coretta Scott King,Explores the life and career of Coretta Scott ...,"[-0.3468349575996399, -0.21785852313041687, -0...",4
302,A tawdry place of salvation,In this first critical study of the work of Ja...,"[-0.11076848208904266, -1.3954136371612549, -0...",4
303,Inside COM,"""Microsoft's Component Object Model (COM) has ...","[-0.4319303333759308, -0.4709661602973938, -0....",4
304,Thunderbird gold,"While visiting his cousin in northern Canada, ...","[0.2797992527484894, 0.21501488983631134, 0.27...",4

## Implementation

In [15]:
process_df(df,workers=2, num_chunks=1000)

Splitting df into chunks

/home/dave/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

skipping chunk 0 (already exists)
skipping chunk 1 (already exists)
skipping chunk 2 (already exists)
skipping chunk 3 (already exists)
skipping chunk 4 (already exists)
skipping chunk 5 (already exists)
skipping chunk 6 (already exists)
skipping chunk 7 (already exists)
skipping chunk 8 (already exists)
skipping chunk 9 (already exists)
skipping chunk 10 (already exists)
skipping chunk 11 (already exists)
skipping chunk 12 (already exists)
skipping chunk 13 (already exists)
skipping chunk 14 (already exists)
skipping chunk 15 (already exists)
skipping chunk 16 (already exists)
skipping chunk 17 (already exists)
skipping chunk 18 (already exists)
skipping chunk 19 (already exists)
skipping chunk 20 (already exists)
skipping chunk 21 (already exists)
skipping chunk 22 (already exists)
skipping chunk 23 (already exists)
skipping chunk 24 (already exists)
skipping chunk 25 (already exists)
skipping chunk 26 (already exists)
skipping chunk 27 (already exists)
skipping chunk 28 (already exists)
skipping chunk 29 (already exists)
skipping chunk 30 (already exists)
skipping chunk 31 (already exists)
skipping chunk 32 (already exists)
skipping chunk 33 (already exists)
skipping chunk 34 (already exists)
skipping chunk 35 (already exists)
skipping chunk 36 (already exists)
skipping chunk 37 (already exists)
skipping chunk 38 (already exists)
skipping chunk 39 (already exists)
skipping chunk 40 (already exists)
skipping chunk 41 (already exists)
skipping chunk 42 (already exists)
skipping chunk 43 (already exists)
skipping chunk 44 (already exists)
skipping chunk 45 (already exists)
skipping chunk 46 (already exists)
skipping chunk 47 (already exists)
skipping chunk 48 (already exists)
skipping chunk 49 (already exists)
skipping chunk 50 (already exists)
skipping chunk 51 (already exists)
skipping chunk 52 (already exists)
skipping chunk 53 (already exists)
skipping chunk 54 (already exists)
skipping chunk 55 (already exists)
skipping chunk 56 (already exists)
skipping chunk 57 (already exists)
skipping chunk 58 (already exists)
skipping chunk 59 (already exists)
skipping chunk 60 (already exists)
skipping chunk 61 (already exists)
skipping chunk 62 (already exists)
skipping chunk 63 (already exists)
skipping chunk 64 (already exists)
skipping chunk 65 (already exists)
skipping chunk 66 (already exists)
skipping chunk 67 (already exists)
skipping chunk 68 (already exists)
skipping chunk 69 (already exists)
skipping chunk 70 (already exists)
skipping chunk 71 (already exists)
skipping chunk 72 (already exists)
skipping chunk 73 (already exists)
skipping chunk 74 (already exists)
skipping chunk 75 (already exists)
skipping chunk 76 (already exists)
skipping chunk 77 (already exists)
skipping chunk 78 (already exists)
skipping chunk 79 (already exists)
skipping chunk 80 (already exists)
skipping chunk 81 (already exists)
skipping chunk 82 (already exists)
skipping chunk 83 (already exists)
skipping chunk 84 (already exists)
skipping chunk 85 (already exists)
skipping chunk 86 (already exists)
skipping chunk 87 (already exists)
skipping chunk 88 (already exists)
skipping chunk 89 (already exists)
skipping chunk 90 (already exists)
skipping chunk 91 (already exists)
skipping chunk 92 (already exists)
skipping chunk 93 (already exists)
skipping chunk 94 (already exists)
skipping chunk 95 (already exists)
skipping chunk 96 (already exists)
skipping chunk 97 (already exists)
skipping chunk 98 (already exists)
skipping chunk 99 (already exists)
skipping chunk 100 (already exists)
skipping chunk 101 (already exists)
skipping chunk 102 (already exists)
skipping chunk 103 (already exists)
skipping chunk 104 (already exists)
skipping chunk 105 (already exists)
skipping chunk 106 (already exists)
skipping chunk 107 (already exists)
skipping chunk 108 (already exists)
skipping chunk 109 (already exists)
skipping chunk 110 (already exists)
skipping chunk 111 (already exists)
skipping chunk 112 (already exists)
skipping chunk 113 (already exists)
skipping chunk 114 (already exists)
skipping chunk 115 (already exists)
skipping chunk 116 (already exists)
skipping chunk 117 (already exists)
skipping chunk 118 (already exists)
skipping chunk 119 (already exists)
skipping chunk 120 (already exists)
skipping chunk 121 (already exists)
skipping chunk 122 (already exists)
skipping chunk 123 (already exists)
skipping chunk 124 (already exists)
skipping chunk 125 (already exists)
skipping chunk 126 (already exists)
skipping chunk 127 (already exists)
skipping chunk 128 (already exists)
skipping chunk 129 (already exists)
skipping chunk 130 (already exists)
skipping chunk 131 (already exists)
skipping chunk 132 (already exists)
skipping chunk 133 (already exists)
skipping chunk 134 (already exists)
skipping chunk 135 (already exists)
skipping chunk 136 (already exists)
skipping chunk 137 (already exists)
skipping chunk 138 (already exists)
skipping chunk 139 (already exists)
skipping chunk 140 (already exists)
skipping chunk 141 (already exists)
skipping chunk 142 (already exists)
skipping chunk 143 (already exists)
skipping chunk 144 (already exists)
skipping chunk 145 (already exists)
skipping chunk 146 (already exists)
skipping chunk 147 (already exists)
skipping chunk 148 (already exists)
skipping chunk 149 (already exists)
skipping chunk 150 (already exists)
skipping chunk 151 (already exists)
skipping chunk 152 (already exists)
skipping chunk 153 (already exists)
skipping chunk 154 (already exists)
skipping chunk 155 (already exists)
skipping chunk 156 (already exists)
skipping chunk 157 (already exists)
skipping chunk 158 (already exists)
skipping chunk 159 (already exists)
skipping chunk 160 (already exists)
skipping chunk 161 (already exists)
skipping chunk 162 (already exists)
skipping chunk 163 (already exists)
skipping chunk 164 (already exists)
skipping chunk 165 (already exists)
skipping chunk 166 (already exists)
skipping chunk 167 (already exists)
skipping chunk 168 (already exists)
skipping chunk 169 (already exists)
skipping chunk 170 (already exists)
skipping chunk 171 (already exists)
skipping chunk 172 (already exists)
skipping chunk 173 (already exists)
skipping chunk 174 (already exists)
skipping chunk 175 (already exists)
skipping chunk 176 (already exists)
skipping chunk 177 (already exists)
skipping chunk 178 (already exists)
skipping chunk 179 (already exists)
skipping chunk 180 (already exists)
skipping chunk 181 (already exists)
skipping chunk 182 (already exists)
skipping chunk 183 (already exists)
skipping chunk 184 (already exists)
skipping chunk 185 (already exists)
skipping chunk 186 (already exists)
skipping chunk 187 (already exists)
skipping chunk 188 (already exists)
skipping chunk 189 (already exists)
skipping chunk 190 (already exists)
skipping chunk 191 (already exists)
skipping chunk 192 (already exists)
skipping chunk 193 (already exists)
skipping chunk 194 (already exists)
skipping chunk 195 (already exists)
skipping chunk 196 (already exists)
skipping chunk 197 (already exists)
skipping chunk 198 (already exists)
skipping chunk 199 (already exists)
skipping chunk 200 (already exists)
skipping chunk 201 (already exists)
skipping chunk 202 (already exists)
skipping chunk 203 (already exists)
skipping chunk 204 (already exists)
skipping chunk 205 (already exists)
skipping chunk 206 (already exists)
skipping chunk 207 (already exists)
skipping chunk 208 (already exists)
skipping chunk 209 (already exists)
skipping chunk 210 (already exists)
skipping chunk 211 (already exists)
skipping chunk 212 (already exists)
skipping chunk 213 (already exists)
skipping chunk 214 (already exists)
skipping chunk 215 (already exists)
skipping chunk 216 (already exists)
skipping chunk 217 (already exists)
skipping chunk 218 (already exists)
skipping chunk 219 (already exists)
skipping chunk 220 (already exists)
skipping chunk 221 (already exists)
skipping chunk 222 (already exists)
skipping chunk 223 (already exists)
skipping chunk 224 (already exists)
skipping chunk 225 (already exists)
skipping chunk 226 (already exists)
skipping chunk 227 (already exists)
skipping chunk 228 (already exists)
skipping chunk 229 (already exists)
skipping chunk 230 (already exists)
skipping chunk 231 (already exists)
skipping chunk 232 (already exists)
skipping chunk 233 (already exists)
skipping chunk 234 (already exists)
skipping chunk 235 (already exists)
skipping chunk 236 (already exists)
skipping chunk 237 (already exists)
skipping chunk 238 (already exists)
skipping chunk 239 (already exists)
skipping chunk 240 (already exists)
skipping chunk 241 (already exists)
skipping chunk 242 (already exists)
skipping chunk 243 (already exists)
skipping chunk 244 (already exists)
skipping chunk 245 (already exists)
skipping chunk 246 (already exists)
skipping chunk 247 (already exists)
skipping chunk 248 (already exists)
skipping chunk 249 (already exists)
skipping chunk 250 (already exists)
skipping chunk 251 (already exists)
skipping chunk 252 (already exists)
skipping chunk 253 (already exists)
skipping chunk 254 (already exists)
skipping chunk 255 (already exists)
skipping chunk 256 (already exists)
skipping chunk 257 (already exists)
skipping chunk 258 (already exists)
skipping chunk 259 (already exists)
skipping chunk 260 (already exists)
skipping chunk 261 (already exists)
skipping chunk 262 (already exists)
skipping chunk 263 (already exists)
skipping chunk 264 (already exists)
skipping chunk 265 (already exists)
skipping chunk 266 (already exists)
skipping chunk 267 (already exists)
skipping chunk 268 (already exists)
skipping chunk 269 (already exists)
skipping chunk 270 (already exists)
skipping chunk 271 (already exists)
skipping chunk 272 (already exists)
skipping chunk 273 (already exists)
skipping chunk 274 (already exists)
skipping chunk 275 (already exists)
skipping chunk 276 (already exists)
skipping chunk 277 (already exists)
skipping chunk 278 (already exists)
skipping chunk 279 (already exists)
skipping chunk 280 (already exists)
skipping chunk 281 (already exists)
skipping chunk 282 (already exists)
skipping chunk 283 (already exists)
skipping chunk 284 (already exists)
skipping chunk 285 (already exists)
skipping chunk 286 (already exists)
skipping chunk 287 (already exists)
skipping chunk 288 (already exists)
skipping chunk 289 (already exists)
skipping chunk 290 (already exists)
skipping chunk 291 (already exists)
skipping chunk 292 (already exists)
skipping chunk 293 (already exists)
skipping chunk 294 (already exists)
skipping chunk 295 (already exists)
skipping chunk 296 (already exists)
skipping chunk 297 (already exists)
skipping chunk 298 (already exists)
skipping chunk 299 (already exists)
skipping chunk 300 (already exists)
skipping chunk 301 (already exists)
skipping chunk 302 (already exists)
skipping chunk 303 (already exists)
skipping chunk 304 (already exists)
skipping chunk 305 (already exists)
skipping chunk 306 (already exists)
skipping chunk 307 (already exists)
skipping chunk 308 (already exists)
skipping chunk 309 (already exists)
skipping chunk 310 (already exists)
skipping chunk 311 (already exists)
skipping chunk 312 (already exists)
skipping chunk 313 (already exists)
skipping chunk 314 (already exists)
skipping chunk 315 (already exists)
skipping chunk 316 (already exists)
skipping chunk 317 (already exists)
skipping chunk 318 (already exists)
skipping chunk 319 (already exists)
skipping chunk 320 (already exists)
skipping chunk 321 (already exists)
skipping chunk 322 (already exists)
skipping chunk 323 (already exists)
skipping chunk 324 (already exists)
skipping chunk 325 (already exists)
skipping chunk 326 (already exists)
skipping chunk 327 (already exists)
skipping chunk 328 (already exists)
skipping chunk 329 (already exists)
skipping chunk 330 (already exists)
skipping chunk 331 (already exists)
skipping chunk 332 (already exists)
skipping chunk 333 (already exists)
skipping chunk 334 (already exists)
skipping chunk 335 (already exists)
skipping chunk 336 (already exists)
skipping chunk 337 (already exists)
skipping chunk 338 (already exists)
skipping chunk 339 (already exists)
skipping chunk 340 (already exists)
skipping chunk 341 (already exists)
skipping chunk 342 (already exists)
skipping chunk 343 (already exists)
skipping chunk 344 (already exists)
skipping chunk 345 (already exists)
skipping chunk 346 (already exists)
skipping chunk 347 (already exists)
skipping chunk 348 (already exists)
skipping chunk 349 (already exists)
skipping chunk 350 (already exists)
skipping chunk 351 (already exists)
skipping chunk 352 (already exists)
skipping chunk 353 (already exists)
skipping chunk 354 (already exists)
skipping chunk 355 (already exists)
skipping chunk 356 (already exists)
skipping chunk 357 (already exists)
skipping chunk 358 (already exists)
skipping chunk 359 (already exists)
skipping chunk 360 (already exists)
skipping chunk 361 (already exists)
skipping chunk 362 (already exists)
skipping chunk 363 (already exists)
skipping chunk 364 (already exists)
skipping chunk 365 (already exists)
skipping chunk 366 (already exists)
skipping chunk 367 (already exists)
skipping chunk 368 (already exists)
skipping chunk 369 (already exists)
skipping chunk 370 (already exists)
skipping chunk 371 (already exists)
skipping chunk 372 (already exists)
skipping chunk 373 (already exists)
skipping chunk 374 (already exists)
skipping chunk 375 (already exists)
skipping chunk 376 (already exists)
skipping chunk 377 (already exists)
skipping chunk 378 (already exists)
skipping chunk 379 (already exists)
skipping chunk 380 (already exists)
skipping chunk 381 (already exists)
skipping chunk 382 (already exists)
skipping chunk 383 (already exists)
skipping chunk 384 (already exists)
skipping chunk 385 (already exists)
skipping chunk 386 (already exists)
skipping chunk 387 (already exists)
skipping chunk 388 (already exists)
skipping chunk 389 (already exists)
skipping chunk 390 (already exists)
skipping chunk 391 (already exists)
skipping chunk 392 (already exists)
skipping chunk 393 (already exists)
skipping chunk 394 (already exists)
skipping chunk 395 (already exists)
skipping chunk 396 (already exists)
skipping chunk 397 (already exists)
skipping chunk 398 (already exists)
skipping chunk 399 (already exists)
skipping chunk 400 (already exists)
skipping chunk 401 (already exists)
skipping chunk 402 (already exists)
skipping chunk 403 (already exists)
skipping chunk 404 (already exists)
skipping chunk 405 (already exists)
skipping chunk 406 (already exists)
skipping chunk 407 (already exists)
skipping chunk 408 (already exists)
skipping chunk 409 (already exists)
skipping chunk 410 (already exists)
skipping chunk 411 (already exists)
skipping chunk 412 (already exists)
skipping chunk 413 (already exists)
skipping chunk 414 (already exists)
skipping chunk 415 (already exists)
skipping chunk 416 (already exists)
skipping chunk 417 (already exists)
skipping chunk 418 (already exists)
skipping chunk 419 (already exists)
skipping chunk 420 (already exists)
skipping chunk 421 (already exists)
skipping chunk 422 (already exists)
skipping chunk 423 (already exists)
skipping chunk 424 (already exists)
skipping chunk 425 (already exists)
skipping chunk 426 (already exists)
skipping chunk 427 (already exists)
skipping chunk 428 (already exists)
skipping chunk 429 (already exists)
skipping chunk 430 (already exists)
skipping chunk 431 (already exists)
skipping chunk 432 (already exists)
skipping chunk 433 (already exists)
skipping chunk 434 (already exists)
skipping chunk 435 (already exists)
skipping chunk 436 (already exists)
skipping chunk 437 (already exists)
skipping chunk 438 (already exists)
skipping chunk 439 (already exists)
skipping chunk 440 (already exists)
skipping chunk 441 (already exists)
skipping chunk 442 (already exists)
skipping chunk 443 (already exists)
skipping chunk 444 (already exists)
skipping chunk 445 (already exists)
skipping chunk 446 (already exists)
skipping chunk 447 (already exists)
skipping chunk 448 (already exists)
skipping chunk 449 (already exists)
skipping chunk 450 (already exists)
skipping chunk 451 (already exists)
skipping chunk 452 (already exists)
skipping chunk 453 (already exists)
skipping chunk 454 (already exists)
skipping chunk 455 (already exists)
skipping chunk 456 (already exists)
skipping chunk 457 (already exists)
skipping chunk 458 (already exists)
skipping chunk 459 (already exists)
skipping chunk 460 (already exists)
skipping chunk 461 (already exists)
skipping chunk 462 (already exists)
skipping chunk 463 (already exists)
skipping chunk 464 (already exists)
skipping chunk 465 (already exists)
skipping chunk 466 (already exists)
skipping chunk 467 (already exists)
skipping chunk 468 (already exists)
skipping chunk 469 (already exists)
skipping chunk 470 (already exists)
skipping chunk 471 (already exists)
skipping chunk 472 (already exists)
skipping chunk 473 (already exists)
skipping chunk 474 (already exists)
skipping chunk 475 (already exists)
skipping chunk 476 (already exists)
skipping chunk 477 (already exists)
skipping chunk 478 (already exists)
skipping chunk 479 (already exists)
skipping chunk 480 (already exists)
skipping chunk 481 (already exists)
skipping chunk 482 (already exists)
skipping chunk 483 (already exists)
skipping chunk 484 (already exists)
skipping chunk 485 (already exists)
skipping chunk 486 (already exists)
skipping chunk 487 (already exists)
skipping chunk 488 (already exists)
skipping chunk 489 (already exists)
skipping chunk 490 (already exists)
skipping chunk 491 (already exists)
skipping chunk 492 (already exists)
skipping chunk 493 (already exists)
skipping chunk 494 (already exists)
skipping chunk 495 (already exists)
skipping chunk 496 (already exists)
skipping chunk 497 (already exists)
skipping chunk 498 (already exists)
skipping chunk 499 (already exists)
skipping chunk 500 (already exists)
skipping chunk 501 (already exists)
skipping chunk 502 (already exists)
skipping chunk 503 (already exists)
skipping chunk 504 (already exists)
skipping chunk 505 (already exists)
skipping chunk 506 (already exists)
skipping chunk 507 (already exists)
skipping chunk 508 (already exists)
skipping chunk 509 (already exists)
skipping chunk 510 (already exists)
skipping chunk 511 (already exists)
skipping chunk 512 (already exists)
skipping chunk 513 (already exists)
skipping chunk 514 (already exists)
skipping chunk 515 (already exists)
skipping chunk 516 (already exists)
skipping chunk 517 (already exists)
skipping chunk 518 (already exists)
skipping chunk 519 (already exists)
skipping chunk 520 (already exists)
skipping chunk 521 (already exists)
skipping chunk 522 (already exists)
skipping chunk 523 (already exists)
skipping chunk 524 (already exists)
skipping chunk 525 (already exists)
skipping chunk 526 (already exists)
skipping chunk 527 (already exists)
skipping chunk 528 (already exists)
skipping chunk 529 (already exists)
skipping chunk 530 (already exists)
skipping chunk 531 (already exists)
skipping chunk 532 (already exists)
skipping chunk 533 (already exists)
skipping chunk 534 (already exists)
skipping chunk 535 (already exists)
skipping chunk 536 (already exists)
skipping chunk 537 (already exists)
skipping chunk 538 (already exists)
skipping chunk 539 (already exists)
skipping chunk 540 (already exists)
skipping chunk 541 (already exists)
skipping chunk 542 (already exists)
skipping chunk 543 (already exists)
skipping chunk 544 (already exists)
skipping chunk 545 (already exists)
skipping chunk 546 (already exists)
skipping chunk 547 (already exists)
skipping chunk 548 (already exists)
skipping chunk 549 (already exists)
skipping chunk 550 (already exists)
skipping chunk 551 (already exists)
skipping chunk 552 (already exists)
skipping chunk 553 (already exists)
skipping chunk 554 (already exists)
skipping chunk 555 (already exists)
skipping chunk 556 (already exists)
skipping chunk 557 (already exists)

Chunk 936: 100%|██████████| 1955/1955 [01:42<00:00, 19.02it/s]
Chunk 937: 100%|██████████| 1955/1955 [02:13<00:00, 14.64it/s]it]
Chunk 938: 100%|██████████| 1955/1955 [02:00<00:00, 16.17it/s]t]
Chunk 939: 100%|██████████| 1955/1955 [02:19<00:00, 13.99it/s]t]
Chunk 940: 100%|██████████| 1955/1955 [02:11<00:00, 14.86it/s]t]
Chunk 941: 100%|██████████| 1955/1955 [02:16<00:00, 14.28it/s]t]
Chunk 942: 100%|██████████| 1955/1955 [02:02<00:00, 15.99it/s]t]
Chunk 943: 100%|██████████| 1955/1955 [02:06<00:00, 15.46it/s]t]
Chunk 944: 100%|██████████| 1955/1955 [02:07<00:00, 15.28it/s]t]
Chunk 945: 100%|██████████| 1955/1955 [02:12<00:00, 14.79it/s]t]
Chunk 946: 100%|██████████| 1955/1955 [02:02<00:00, 15.97it/s]]
Chunk 947: 100%|██████████| 1955/1955 [02:06<00:00, 15.48it/s]]
Chunk 948: 100%|██████████| 1955/1955 [02:12<00:00, 14.73it/s]]
Chunk 949: 100%|██████████| 1955/1955 [02:15<00:00, 14.40it/s]]
Chunk 950: 100%|██████████| 1955/1955 [02:02<00:00, 15.99it/s]]
Chunk 951: 100%|██████████| 1955/1955 [02:04<00:00, 15.65it/s]]
Chunk 952: 100%|██████████| 1955/1955 [02:12<00:00, 14.80it/s]]
Chunk 953: 100%|██████████| 1955/1955 [02:14<00:00, 14.53it/s]]
Chunk 954: 100%|██████████| 1955/1955 [02:07<00:00, 15.36it/s]]
Chunk 955: 100%|██████████| 1955/1955 [02:03<00:00, 15.78it/s]]
Chunk 956: 100%|██████████| 1955/1955 [02:12<00:00, 14.72it/s]]
Chunk 957: 100%|██████████| 1955/1955 [02:14<00:00, 14.57it/s]]
Chunk 958: 100%|██████████| 1955/1955 [02:04<00:00, 15.74it/s]]
Chunk 959: 100%|██████████| 1955/1955 [02:06<00:00, 15.46it/s]]
Chunk 960: 100%|██████████| 1955/1955 [02:14<00:00, 14.52it/s]]
Chunk 961: 100%|██████████| 1955/1955 [02:13<00:00, 14.62it/s]]
Chunk 962: 100%|██████████| 1955/1955 [02:07<00:00, 15.34it/s]]
Chunk 963: 100%|██████████| 1955/1955 [02:05<00:00, 15.61it/s]]
Chunk 964: 100%|██████████| 1955/1955 [02:13<00:00, 14.62it/s]]
Chunk 965: 100%|██████████| 1955/1955 [02:16<00:00, 14.36it/s]]
Chunk 966: 100%|██████████| 1955/1955 [02:06<00:00, 15.47it/s]]
Chunk 967: 100%|██████████| 1955/1955 [02:08<00:00, 15.18it/s]]
Chunk 968: 100%|██████████| 1955/1955 [02:12<00:00, 14.71it/s]]
Chunk 969: 100%|██████████| 1955/1955 [02:15<00:00, 14.44it/s]]
Chunk 970: 100%|██████████| 1955/1955 [02:06<00:00, 15.52it/s]]
Chunk 971: 100%|██████████| 1955/1955 [02:07<00:00, 15.33it/s]]
Chunk 972: 100%|██████████| 1955/1955 [02:17<00:00, 14.24it/s]]
Chunk 973: 100%|██████████| 1955/1955 [02:12<00:00, 14.80it/s]]
Chunk 974: 100%|██████████| 1955/1955 [02:08<00:00, 15.21it/s]]
Chunk 975: 100%|██████████| 1955/1955 [02:09<00:00, 15.06it/s]]
Chunk 976: 100%|██████████| 1955/1955 [02:15<00:00, 14.45it/s]]
Chunk 977: 100%|██████████| 1955/1955 [02:08<00:00, 15.23it/s]]
Chunk 978: 100%|██████████| 1955/1955 [02:05<00:00, 15.64it/s]]
Chunk 979: 100%|██████████| 1955/1955 [02:11<00:00, 14.87it/s]]
Chunk 980: 100%|██████████| 1955/1955 [02:16<00:00, 14.37it/s]]
Chunk 981: 100%|██████████| 1955/1955 [02:08<00:00, 15.24it/s]]
Chunk 982: 100%|██████████| 1955/1955 [02:06<00:00, 15.48it/s]]
Chunk 983: 100%|██████████| 1955/1955 [02:10<00:00, 15.01it/s]]
Chunk 984: 100%|██████████| 1955/1955 [02:18<00:00, 14.15it/s]]
Chunk 985: 100%|██████████| 1955/1955 [02:05<00:00, 15.58it/s]]
Chunk 986: 100%|██████████| 1955/1955 [02:07<00:00, 15.33it/s]]
Chunk 987: 100%|██████████| 1955/1955 [02:12<00:00, 14.73it/s]]
Chunk 988: 100%|██████████| 1955/1955 [02:20<00:00, 13.96it/s]]
Chunk 989: 100%|██████████| 1955/1955 [02:06<00:00, 15.45it/s]]
Chunk 990: 100%|██████████| 1955/1955 [02:07<00:00, 15.28it/s]it]
Chunk 991: 100%|██████████| 1955/1955 [02:09<00:00, 15.05it/s]it]
Chunk 992: 100%|██████████| 1955/1955 [02:18<00:00, 14.12it/s]it]
Chunk 993: 100%|██████████| 1955/1955 [02:09<00:00, 15.13it/s]it]
Chunk 994: 100%|██████████| 1955/1955 [02:08<00:00, 15.25it/s]it]
Chunk 995: 100%|██████████| 1955/1955 [02:13<00:00, 14.69it/s]it]
Chunk 996: 100%|██████████| 1955/1955 [02:19<00:00, 14.02it/s]it]
Chunk 997: 100%|██████████| 1955/1955 [02:12<00:00, 14.74it/s]it]
Chunk 998: 100%|██████████| 1955/1955 [02:09<00:00, 15.05it/s]it]
Chunk 999: 100%|██████████| 1955/1955 [02:00<00:00, 16.22it/s]it]
Filtering rows: 100%|██████████| 64/64 [1:11:21<00:00, 66.90s/it]

processing tool: 4282.260821819305  seconds

,title,description,embeddings
0,Le pont,A complete French curriculum that provides a b...,None
1,The Mysteries of Udolpho,<p>The Mysteries of Udolpho (1794) is a Gothic...,None
2,America at war,Presents America's wartime history from the Re...,None
3,Philosophy of Mannerism,Sjoerd van Tuinen argues for the inseparabilit...,None
4,Prehistoric warfare in the American Southwest,"Most people today, including many archaeologis...",None
...,...,...,...
125115,NaN,Q/微信859034112办理毕业证成绩单丶使馆和教育部学历学位认证★诚招代理★\n英华教育...,"[0.20330633223056793, 0.4392056465148926, 0.82..."
125116,NaN,Books mentioned by Mercedes Shepard English in...,"[-0.040287502110004425, -0.44669461250305176, ..."
125117,NaN,"The noise of time, Theodosia. The Egyptian sta...","[-0.8145684599876404, 0.44507068395614624, -0...."
125118,NaN,Author databar,"[-0.5466983318328857, -0.6076515316963196, 0.1..."
125119,NaN,"Presents the adventures of Mowgli, a boy reare...","[-0.3725143373012543, -0.3169153928756714, 0.2..."